version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: on-failure
    environment:
      - SERVICES=ssm
      - HOSTNAME=localhost
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - '4566:4566'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./populate.sh:/etc/localstack/init/ready.d/script.sh
    networks:
      - localstack_network

networks:
  localstack_network:
    driver: bridge

